package constants

import "github.com/teamhanko/hanko/backend/flowpilot"

const (
	StateError                                 flowpilot.StateName = "error"
	StateLoginInit                             flowpilot.StateName = "login_init"
	StateLoginMethodChooser                    flowpilot.StateName = "login_method_chooser"
	StateLoginPasskey                          flowpilot.StateName = "login_passkey"
	StateLoginPassword                         flowpilot.StateName = "login_password"
	StateLoginPasswordRecovery                 flowpilot.StateName = "login_password_recovery"
	StateOnboardingCreatePasskey               flowpilot.StateName = "onboarding_create_passkey"
	StateOnboardingCreatePasskeyConditional    flowpilot.StateName = "onboarding_create_passkey_conditional"
	StateOnboardingVerifyPasskeyAttestation    flowpilot.StateName = "onboarding_verify_passkey_attestation"
	StatePasscodeConfirmation                  flowpilot.StateName = "passcode_confirmation"
	StatePasswordCreation                      flowpilot.StateName = "password_creation"
	StatePasswordCreationConditional           flowpilot.StateName = "password_creation_conditional"
	StatePreflight                             flowpilot.StateName = "preflight"
	StateProfileAccountDeleted                 flowpilot.StateName = "account_deleted"
	StateProfileInit                           flowpilot.StateName = "profile_init"
	StateProfileWebauthnCredentialVerification flowpilot.StateName = "webauthn_credential_verification"
	StateRegisterPasskey                       flowpilot.StateName = "register_passkey"
	StateRegistrationInit                      flowpilot.StateName = "registration_init"
	StateRegistrationMethodChooser             flowpilot.StateName = "registration_method_chooser"
	StateSuccess                               flowpilot.StateName = "success"
	StateThirdPartyOAuth                       flowpilot.StateName = "thirdparty_oauth"
)

const (
	ActionAccountDelete                          flowpilot.ActionName = "account_delete"
	ActionBack                                   flowpilot.ActionName = "back"
	ActionContinueToPasscodeConfirmation         flowpilot.ActionName = "continue_to_passcode_confirmation"
	ActionContinueToPasscodeConfirmationRecovery flowpilot.ActionName = "continue_to_passcode_confirmation_recovery"
	ActionContinueToPasskeyRegistration          flowpilot.ActionName = "continue_to_passkey_registration"
	ActionContinueToPasswordLogin                flowpilot.ActionName = "continue_to_password_login"
	ActionContinueToPasswordRegistration         flowpilot.ActionName = "continue_to_password_registration"
	ActionContinueWithLoginIdentifier            flowpilot.ActionName = "continue_with_login_identifier"
	ActionEmailCreate                            flowpilot.ActionName = "email_create"
	ActionEmailDelete                            flowpilot.ActionName = "email_delete"
	ActionEmailSetPrimary                        flowpilot.ActionName = "email_set_primary"
	ActionEmailVerify                            flowpilot.ActionName = "email_verify"
	ActionExchangeToken                          flowpilot.ActionName = "exchange_token"
	ActionPasswordDelete                         flowpilot.ActionName = "password_delete"
	ActionPasswordLogin                          flowpilot.ActionName = "password_login"
	ActionPasswordRecovery                       flowpilot.ActionName = "password_recovery"
	ActionPasswordSet                            flowpilot.ActionName = "password_set"
	ActionRegisterClientCapabilities             flowpilot.ActionName = "register_client_capabilities"
	ActionRegisterLoginIdentifier                flowpilot.ActionName = "register_login_identifier"
	ActionRegisterPassword                       flowpilot.ActionName = "register_password"
	ActionResendPasscode                         flowpilot.ActionName = "resend_passcode"
	ActionSkip                                   flowpilot.ActionName = "skip"
	ActionThirdPartyOAuth                        flowpilot.ActionName = "thirdparty_oauth"
	ActionUsernameSet                            flowpilot.ActionName = "username_set"
	ActionVerifyPasscode                         flowpilot.ActionName = "verify_passcode"
	ActionWebauthnCredentialCreate               flowpilot.ActionName = "webauthn_credential_create"
	ActionWebauthnCredentialDelete               flowpilot.ActionName = "webauthn_credential_delete"
	ActionWebauthnCredentialRename               flowpilot.ActionName = "webauthn_credential_rename"
	ActionWebauthnGenerateCreationOptions        flowpilot.ActionName = "webauthn_generate_creation_options"
	ActionWebauthnGenerateRequestOptions         flowpilot.ActionName = "webauthn_generate_request_options"
	ActionWebauthnVerifyAssertionResponse        flowpilot.ActionName = "webauthn_verify_assertion_response"
	ActionWebauthnVerifyAttestationResponse      flowpilot.ActionName = "webauthn_verify_attestation_response"
)
