resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
vars:
  - fieldref:
      fieldpath: metadata.labels.fqdn
    name: MAILHOG_FQDN
    objref:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      name: mailhog
