
openapi: 3.0.0
info:
  version: '0.2.0'
  title: 'Hanko Admin API'
  description: |
    ## Introduction

    This is the OpenAPI specification for the [Hanko Admin API](https://github.com/teamhanko/hanko/blob/main/backend/README.md#start-private-api).

    ## Authentication

    The Admin API must be protected by an access management system.

    ---

  contact:
    email: developers@hanko.io
  license:
    name: AGPL-3.0-or-later
    url: https://www.gnu.org/licenses/agpl-3.0.txt
externalDocs:
  description: More about Hanko
  url: https://github.com/teamhanko/hanko
servers:
  - url: 'localhost:3000'
paths:
  /users:
    get:
      summary: 'Get a list of users'
      operationId: listUsers
      tags:
        - User Management
      responses:
        '200':
          description: 'Details about users'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /users/{id}:
    patch:
      summary: 'Update a user by ID'
      operationId: updateUser
      tags:
        - User Management
      parameters:
        - name: id
          in: path
          description: ID of the user
          required: true
          schema:
            $ref: '#/components/schemas/UUID4'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                status:
                  type: string
                  enum: [active, inactive]
      responses:
        '200':
          description: 'Updated user details'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      summary: 'Delete a user by ID'
      operationId: deleteUser
      tags:
        - User Management
      parameters:
        - name: id
          in: path
          description: ID of the user
          required: true
          schema:
            $ref: '#/components/schemas/UUID4'
      responses:
        '204':
          description: 'Deleted'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /audit_logs:
    get:
      summary: 'Get a list of audit logs'
      operationId: listAuditLogs
      tags:
        - Audit Logs
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: The page which should be returned
        - in: query
          name: per_page
          schema:
            type: integer
            default: 20
          description: The number of returned items
        - in: query
          name: start_time
          schema:
            type: string
            example: 2022-09-12T12:48:48Z
          description: Date and time from which the logs are included
        - in: query
          name: end_time
          schema:
            type: string
            example: 2022-09-15T12:48:48Z
          description: Date and time to which the logs are included
      responses:
        '200':
          description: 'Details about audit logs'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AuditLog'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 400
            message: Bad Request
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 500
            message: Internal Server Error
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 404
            message: Not found
  schemas:
    User:
      type: object
      properties:
        id:
          description: The ID of the user
          allOf:
            - $ref: '#/components/schemas/UUID4'
        email:
          description: The email address of the user
          type: string
          format: email
        created_at:
          description: Time of creation of the the user
          type: string
          format: date-time
        updated_at:
          description: Time of last update of the user
          type: string
          format: date-time
        verified:
          description: Indicates whether the user's email address was verified
          type: boolean
        webauthn_credentials:
          description: List of registered Webauthn credentials
          type: array
          items:
            type: object
            properties:
              id:
                description: The ID of the Webauthn credential
                type: string
                format: base64url
                example: Meprtysj5ZZrTlg0qiLbsZ168OtQMeGVAikVy2n1hvvG...
    AuditLog:
      type: object
      required:
        - id
        - type
        - meta_http_request_id
        - meta_source_ip
        - meta_user_agent
        - created_at
        - updated_at
      properties:
        id:
          description: The ID of the audit log
          allOf:
            - $ref: '#/components/schemas/UUID4'
        type:
          description: The type of the audit log
          type: string
          enum:
            - user_created
            - password_set_succeeded
            - password_set_failed
            - password_login_succeeded
            - password_login_failed
            - passcode_login_init_succeeded
            - passcode_login_init_failed
            - passcode_login_final_succeeded
            - passcode_login_final_failed
            - webauthn_registration_init_succeeded
            - webauthn_registration_init_failed
            - webauthn_registration_final_succeeded
            - webauthn_registration_final_failed
            - webauthn_authentication_init_succeeded
            - webauthn_authentication_init_failed
            - webauthn_authentication_final_succeeded
            - webauthn_authentication_final_failed
        error:
          description: A more detailed message why something failed
          type: string
        meta_http_request_id:
          description: The ID of the corresponding http request
          type: string
          example: 0a2xsrhlhiQv49FIpq8KV8uQVq6ky9Bw
        meta_source_ip:
          description: The IP from where the http request came from
          type: string
          format: ip-address
          example: 172.27.0.1
        meta_user_agent:
          description: The user agent from where the http request came from
          type: string
        actor_user_id:
          description: The userID from the actor
          allOf:
            - $ref: '#/components/schemas/UUID4'
        actor_email:
          description: The email from the actor
          type: string
          format: email
        created_at:
          description: Time of creation of the the audit log
          type: string
          format: date-time
          example: 2022-09-14T12:15:09.788784Z
        updated_at:
          description: Time of last update of the audit log
          type: string
          format: date-time
          example: 2022-09-14T12:15:09.788784Z
    UUID4:
      type: string
      format: uuid4
      example: c339547d-e17d-4ba7-8a1d-b3d5a4d17c1c
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
