openapi: 3.0.3
info:
  title: Flow API
  description: Flow API
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /registration:
    post:
      description: Registration
      parameters:
        - in: query
          name: flowpilot_action
          schema:
            type: string
          example: register_client_capabilities@1c456375-4dde-48ba-bb03-5845aec350ce
      responses:
        200:
          $ref: "#/components/responses/FlowResponse"
  /login:
    post:
      description: Start Login Flow
      parameters:
        - in: query
          name: flowpilot_action
          schema:
            type: string
          example: register_client_capabilities@1c456375-4dde-48ba-bb03-5845aec350ce
      responses:
        200:
          $ref: "#/components/responses/FlowResponse"
  /profile:
    post:
      description: Profile
      parameters:
        - in: query
          name: flowpilot_action
          schema:
            type: string
          example: register_client_capabilities@1c456375-4dde-48ba-bb03-5845aec350ce
      responses:
        200:
          $ref: "#/components/responses/FlowResponse"

components:
  schemas:
    Action:
      description: Action
      type: object
      properties:
        action:
          type: string
        href:
          type: string
        description:
          type: string
        inputs:
          $ref: "#/components/schemas/Inputs"
    Actions:
      description: Actions
      type: object
      additionalProperties:
        $ref: "#/components/schemas/Action"
    Input:
      description: Input
      type: object
      properties:
        hidden:
          type: boolean
        name:
          type: string
        type:
          type: string
        required:
          type: boolean
    Inputs:
      description: Inputs
      type: object
      additionalProperties:
        $ref: "#/components/schemas/Input"
    Payload:
      description: Payload
      type: object
      additionalProperties: true
  responses:
    FlowResponse:
      description: Flow Response
      content:
        application/json:
          examples:
            gut:
              $ref: "#/components/examples/gute_flow_response"
            schlecht:
              $ref: "#/components/examples/schlechte_flow_response"
          schema:
            type: object
            properties:
              actions:
                $ref: "#/components/schemas/Actions"
              flow_path:
                type: string
              name:
                type: string
              payload:
                $ref: "#/components/schemas/Payload"
              status:
                type: integer
  examples:
    schlechte_flow_response:
      value:
        actions:
          gute_action:
            action: schlechte_action
            href: /schlechte_action
            description: Eine schlechte Action
            inputs:
              guter_input:
                hidden: true
                name: schlechte_input
                type: string
                required: true
        flow_path: /schlechter_flow
        name: "Schlechter Flow"
        payload:
          pay: load
        status: 200
    gute_flow_response:
      value:
        actions:
          gute_action:
            action: gute_action
            href: /gute_action
            description: Eine gute Action
            inputs:
              guter_input:
                hidden: true
                name: guter_input
                type: string
                required: true
        flow_path: /guter_flow
        name: "Guter Flow"
        payload:
          pay: load
        status: 200
