package actions

import (
	"github.com/teamhanko/hanko/backend/flow_api_basic_construct/common"
	"github.com/teamhanko/hanko/backend/flowpilot"
)

func NewSendWAAssertionResponse() SendWAAssertionResponse {
	return SendWAAssertionResponse{}
}

type SendWAAssertionResponse struct{}

func (m SendWAAssertionResponse) GetName() flowpilot.ActionName {
	return common.ActionSendWAAssertionResponse
}

func (m SendWAAssertionResponse) GetDescription() string {
	return "Send the result which was generated by using a webauthn credential."
}

func (m SendWAAssertionResponse) Initialize(c flowpilot.InitializationContext) {
	c.AddInputs(flowpilot.StringInput("public_key").Required(true))
	// TODO:
}

func (m SendWAAssertionResponse) Execute(c flowpilot.ExecutionContext) error {
	if valid := c.ValidateInputData(); !valid {
		return c.ContinueFlowWithError(c.GetCurrentState(), flowpilot.ErrorFormDataInvalid)
	}

	// TODO:

	return c.ContinueFlow(common.StateSuccess)
}
