package actions

import (
	"github.com/teamhanko/hanko/backend/flow_api_basic_construct/common"
	"github.com/teamhanko/hanko/backend/flowpilot"
)

func NewSendWAAttestationResponse() SendWAAttestationResponse {
	return SendWAAttestationResponse{}
}

type SendWAAttestationResponse struct{}

func (m SendWAAttestationResponse) GetName() flowpilot.ActionName {
	return common.ActionSendWAAttestationResponse
}

func (m SendWAAttestationResponse) GetDescription() string {
	return "Send the result which was generated by creating a webauthn credential."
}

func (m SendWAAttestationResponse) Initialize(c flowpilot.InitializationContext) {
	c.AddInputs(flowpilot.StringInput("public_key").Required(true))
	// TODO:
}

func (m SendWAAttestationResponse) Execute(c flowpilot.ExecutionContext) error {
	if valid := c.ValidateInputData(); !valid {
		return c.ContinueFlowWithError(c.GetCurrentState(), flowpilot.ErrorFormDataInvalid)
	}

	// TODO:

	return c.ContinueFlow(common.StateSuccess)
}
