---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: hanko
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
  name: postgres-pv-claim
  namespace: hanko
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M