passcode:
  smtp:
    host: smtp.example.com
    user: example
    password: example
database:
  url: postgres://postgres:123456@127.0.0.1:5432/dummy
secrets:
  keys:
    - abcedfghijklmnopqrstuvwxyz
service:
  name: Hanko Authentication Service
