server:
  public:
    address: :8000
    cors:
      allow_origins:
        - https://cloud.hanko.test
      unsafe_wildcard_origin_allowed: false
  admin:
    address: :8001
    cors:
      allow_origins: []
      unsafe_wildcard_origin_allowed: false
database:
  user: hanko
  password: hanko
  host: localhost
  port: 5432
  dialect: postgres
  url: postgres://postgres:123456@127.0.0.1:5432/dummy
secrets:
  keys:
    - abcedfghijklmnopqrstuvwxyz
service:
  name: Hanko Authentication Service
smtp:
  host: smtp.example.com
  port: 4789
  user: example
  password: example
  from_address: no-reply@hanko.io
  from_name: Hanko Cloud
session:
  enable_auth_token_header: false
  lifespan: 24h
  cookie:
    name: ""
    domain: cloud.hanko.io
    http_only: true
    same_site: strict
    secure: true
  issuer: ""
  audience: []
audit_log:
  console_output:
    enabled: false
    output: stdout
  storage:
    enabled: true
third_party:
  providers:
    google:
      enabled: false
      client_id: ""
      secret: ""
  redirect_url: ""
  allowed_redirect_urls: []
rate_limiter:
  enabled: true
  store: in_memory
  redis: null
  passcode:
    tokens: 3
    interval: 1m0s
  password:
    tokens: 3
    interval: 1m0s
  token:
    tokens: 3
    interval: 1m0s
webauthn:
  relying_party:
    id: "cloud.hanko.io"
    origins:
      - "https://cloud.hanko.io"
      - "https://app.cloud.hanko.io"
    display_name: "Hanko Cloud"
    timeouts:
      registration: 300000
      authentication: 300000
    user_verification:
      passkey: "preferred"
      security_key: "discouraged"
password:
  enabled: "disabled|optional|required"
  min_length: 8
identifier:
  username:
    enabled: "disabled|optional|required"
    max_length: 255
    min_length: 3
    allowed_characters: "abcdefghijklmnopqrstuvwxyz123456789-_."
  email:
    enabled: "disabled|optional|required"
    verification: true # maybe we should also consider "disabled|optional|required" or is false interpreted as optional and true as required (and disabled does not exist)
2fa:
  enabled: "disabled|optional|required"
  methods:
    - totp
    - security_key
  recovery_codes:
    enabled: "disabled|optional"
passcode:
  enabled: true
  ttl: 300
account:
  max_email_count: 5
  allow_deletion: true
  allow_signup: true
passkey:
  onboarding_enabled: true
