apiVersion: apps/v1
kind: Deployment
metadata:
  name: hanko-quickstart
  namespace: hanko-tenant
  labels:
    app: hanko-quickstart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hanko-quickstart
  template:
    metadata:
      labels:
        app: hanko-quickstart
    spec:
      containers:
        - name: hanko-quickstart
          image: ghcr.io/teamhanko/hanko/quickstart:main
          imagePullPolicy: IfNotPresent
          env:
            - name: HANKO_URL
              value: https://hanko.quickstart.test
            - name: HANKO_URL_INTERNAL
              value: http://hanko-public.svc
            - name: HANKO_ELEMENT_URL
              value: https://elements.quickstart.test/elements.js
            - name: HANKO_FRONTEND_SDK_URL
              value: https://elements.quickstart.test/sdk.modern.js
          ports:
            - name: http-public
              containerPort: 8080
              protocol: TCP
