description: "Create a bug report"
labels:
  - bug
name: "Bug Report"
body:
  - attributes:
      value: "Thank you for taking the time to fill out this bug report!\n"
    type: markdown
  - attributes:
      label: Checklist
      options:
        - label:
            "I could not find a solution in the existing issues or docs."
          required: true
        - label:
            "I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md)."
          required: true
    id: checklist
    type: checkboxes
  - attributes:
      description: "A clear and concise description of what the bug is."
      label: "Describe the bug"
      placeholder: "Tell us what you see!"
    id: describe-bug
    type: textarea
    validations:
      required: true
  - attributes:
      label: Reproducing the bug
      description: |
        Clear, formatted, and easy to follow steps to reproduce the behavior:
      placeholder: |
        Steps to reproduce the behavior:

        1. Run `docker run ....`
        2. Make API Request to with `curl ...`
        3. Request fails with response: `{"some": "error"}`
    id: reproduce-bug
    type: textarea
    validations:
      required: true
  - attributes:
      label: Logs
      description:
        "Please copy and paste any relevant log output. This will be
        automatically formatted into code, so no need for backticks. Please
        redact any sensitive information!"
      render: Shell
    id: logs
    type: textarea
  - attributes:
      label: Configuration
      description:
        "Please copy and paste any relevant configuration. This will be
        automatically formatted into code, so no need for backticks. Please
        redact any sensitive information!"
      render: yml
      placeholder: |
        server:
          public:
            address: :8080
    id: config
    type: textarea
  - attributes:
      label: Hanko Version
      description: "What version of our software are you running?"
    id: version
    type: input
    validations:
      required: true
  - attributes:
      label: OS
      description: "On which operating system are you observing this issue?"
      options:
        - macOS
        - Linux
        - Windows
        - Other
    id: operating-system
    type: dropdown
  - attributes:
      label: OS Version
      description: "Which operating system version are you using?"
    id: operating-system-version
    type: textarea
  - attributes:
      label: Environment
      description: "In which environment are you deploying/running the application(s)?"
      options:
        - Docker
        - Docker Compose
        - Binary/Build & Run from Source
        - Other (e.g. Kubernetes)
    id: deployment
    type: dropdown
  - attributes:
      description: "Add any other context (Links, References, Screenshots, Files) pertaining to the problem here."
      label: Additional Context
    id: additional
    type: textarea
