blank_issues_enabled: false
contact_links:
  - name: Hanko Slack Community
    url: https://hanko.io/community
    about:
      If you have general questions or questions on integrating hanko please ask them in our Community Slack.
