description:
  "Make a feature request"
labels:
  - enhancement
name: "Feature Request"
body:
  - attributes:
      value: |
        Thank you for making a feature request for this project!
    type: markdown
  - attributes:
      label: Checklist
      options:
        - label:
            "I could not find a solution in the existing issues or docs."
          required: true
        - label:
            "I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md)."
          required: true
    id: checklist
    type: checkboxes
  - attributes:
      label: Description
      description:
        "Is your feature request related to a problem? Please describe."
      placeholder:
        "A clear and concise description of what the problem is. Ex. I'm always
        frustrated when [...]"
    id: problem
    type: textarea
    validations:
      required: true
  - attributes:
      description: |
        Describe the solution you'd like to see implemented
      placeholder: |
        A clear and concise description of what you want to happen.
      label: "Describe your ideal solution"
    id: solution
    type: textarea
    validations:
      required: true
  - attributes:
      label: Workarounds or alternatives
      description: "Describe alternatives you've considered"
    id: alternatives
    type: textarea
    validations:
      required: true
  - attributes:
      label: Hanko Version
      description: "What version of our software are you running?"
    id: version
    type: input
    validations:
      required: true
  - attributes:
      label: Additional Context
      description:
        "Add any other context or screenshots about the feature request here."
    id: additional
    type: textarea
