package schema

import (
	"bytes"
	"encoding/json"
	"fmt"
	"log"
	"os"

	"github.com/invopop/jsonschema"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

func NewGenerateManagementAPICommand() *cobra.Command {
	var output string

	cmd := &cobra.Command{
		Use:   "management-api",
		Short: "Regenerate the config.TenantConfig-derived schemas in the Management API OpenAPI spec",
		Long: `Reflects config.TenantConfig and rewrites the generated portion of the Management API
OpenAPI spec's components.schemas — everything except the hand-written envelope/DTO schemas
(see handWrittenManagementAPISchemas), which are left untouched. Run this after changing anything
under backend/config that config.TenantConfig depends on.`,
		Run: func(cmd *cobra.Command, args []string) {
			generated, err := buildManagementAPISchemas()
			if err != nil {
				log.Fatal(err)
			}

			if err := spliceGeneratedSchemas(output, generated); err != nil {
				log.Fatal(err)
			}

			log.Printf("management API schema regenerated at: %s\n", output)
		},
	}

	cmd.Flags().StringVarP(
		&output, "output",
		"o",
		"docs/management-api.yaml",
		"OpenAPI spec file to update in place")

	return cmd
}

const managementAPIGeneratedSectionComment = "Generated by `go run . schema generate management-api` " +
	"from config.TenantConfig — do not edit below this line."

// spliceGeneratedSchemas rewrites path's components.schemas: entries in handWrittenManagementAPISchemas
// are kept exactly as found (any hand-written comments/formatting included), everything else is
// replaced by generated, in order.
func spliceGeneratedSchemas(path string, generated []generatedSchema) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("failed to read %s: %w", path, err)
	}

	var doc yaml.Node
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		return fmt.Errorf("failed to parse %s: %w", path, err)
	}

	schemasNode, err := findSchemasNode(&doc)
	if err != nil {
		return fmt.Errorf("failed to locate components.schemas in %s: %w", path, err)
	}

	handWritten := make(map[string]bool, len(handWrittenManagementAPISchemas))
	for _, name := range handWrittenManagementAPISchemas {
		handWritten[name] = true
	}

	kept := make([]*yaml.Node, 0, len(schemasNode.Content))
	seen := make(map[string]bool, len(handWrittenManagementAPISchemas))
	for i := 0; i+1 < len(schemasNode.Content); i += 2 {
		keyNode := schemasNode.Content[i]
		valueNode := schemasNode.Content[i+1]
		if handWritten[keyNode.Value] {
			keyNode.HeadComment = ""
			kept = append(kept, keyNode, valueNode)
			seen[keyNode.Value] = true
		}
	}
	for _, name := range handWrittenManagementAPISchemas {
		if !seen[name] {
			return fmt.Errorf("hand-written schema %q not found in %s — was it renamed or removed?", name, path)
		}
	}

	for i, g := range generated {
		valueNode, err := schemaToYAMLNode(g.schema)
		if err != nil {
			return fmt.Errorf("failed to convert schema %q: %w", g.name, err)
		}

		keyNode := &yaml.Node{Kind: yaml.ScalarNode, Value: g.name}
		if i == 0 {
			keyNode.HeadComment = managementAPIGeneratedSectionComment
		}
		kept = append(kept, keyNode, valueNode)
	}

	schemasNode.Content = kept

	out, err := marshalYAMLDocument(&doc)
	if err != nil {
		return fmt.Errorf("failed to marshal %s: %w", path, err)
	}

	return os.WriteFile(path, out, 0644)
}

// schemaToYAMLNode converts a *jsonschema.Schema to a *yaml.Node by marshaling it to JSON (which
// invopop does in the field order declared on the Go struct, via its ordered Properties map) and
// decoding that JSON as YAML — valid JSON is valid YAML, and the decoder preserves the JSON's key
// order in the resulting node tree, which a Go map could not.
func schemaToYAMLNode(s *jsonschema.Schema) (*yaml.Node, error) {
	data, err := json.Marshal(s)
	if err != nil {
		return nil, err
	}

	var doc yaml.Node
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return nil, err
	}

	if doc.Kind == yaml.DocumentNode && len(doc.Content) == 1 {
		return doc.Content[0], nil
	}

	return &doc, nil
}

func mappingValue(node *yaml.Node, key string) *yaml.Node {
	if node == nil || node.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(node.Content); i += 2 {
		if node.Content[i].Value == key {
			return node.Content[i+1]
		}
	}
	return nil
}

func findSchemasNode(doc *yaml.Node) (*yaml.Node, error) {
	if doc.Kind != yaml.DocumentNode || len(doc.Content) != 1 {
		return nil, fmt.Errorf("unexpected YAML document structure")
	}

	root := doc.Content[0]

	components := mappingValue(root, "components")
	if components == nil {
		return nil, fmt.Errorf("no top-level \"components\" key")
	}

	schemas := mappingValue(components, "schemas")
	if schemas == nil {
		return nil, fmt.Errorf("no \"components.schemas\" key")
	}

	return schemas, nil
}

func marshalYAMLDocument(doc *yaml.Node) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)

	if err := enc.Encode(doc); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
