package shared

const (
	StashPathEmail                                  = "email"
	StashPathEmailVerified                          = "email_verified"
	StashPathLoginMethod                            = "login_method"
	StashPathLoginOnboardingCreateEmail             = "login_onboarding_create_email"
	StashPathLoginOnboardingScheduled               = "login_onboarding_scheduled"
	StashPathMFAUsageMethod                         = "mfa_method"
	StashPathCreateMFAOnlyCredential                = "create_mfa_only_credential"
	StashPathNewPassword                            = "new_password"
	StashPathOTPSecret                              = "otp_secret"
	StashPathOTPImageSource                         = "otp_image_src"
	StashPathPasscodeEmail                          = "sticky.passcode_email"
	StashPathPasscodeID                             = "sticky.passcode_id"
	StashPathPasscodeTemplate                       = "passcode_template"
	StashPathPasswordRecoveryPending                = "pw_recovery_pending"
	StashPathSkipUserCreation                       = "skip_user_creation"
	StashPathUserHasEmails                          = "user_has_emails"
	StashPathUserHasOTPSecret                       = "user_hat_otp_secret"
	StashPathUserHasPasskey                         = "user_has_passkey"
	StashPathUserHasPassword                        = "user_has_password"
	StashPathUserHasSecurityKey                     = "user_has_security_key"
	StashPathUserHasUsername                        = "user_has_username"
	StashPathUserHasWebauthnCredential              = "user_has_webauthn_credential"
	StashPathUserID                                 = "user_id"
	StashPathUserIdentification                     = "user_identification"
	StashPathUsername                               = "username"
	StashPathWebauthnAvailable                      = "webauthn_available"
	StashPathWebauthnConditionalMediationAvailable  = "webauthn_conditional_mediation_available"
	StashPathWebauthnCredentials                    = "webauthn_credentials"
	StashPathWebauthnPlatformAuthenticatorAvailable = "webauthn_platform_authenticator_available"
	StashPathWebauthnSessionDataID                  = "webauthn_session_data_id"
)
