package shared

const (
	StashPathEmail                                  = "email"
	StashPathEmailVerified                          = "email_verified"
	StashPathLoginMethod                            = "login_method"
	StashPathLoginOnboardingCreateEmail             = "login_onboarding_create_email"
	StashPathLoginOnboardingScheduled               = "login_onboarding_scheduled"
	StashPathMFAMethod                              = "mfa_method"
	StashPathNewPassword                            = "new_password"
	StashPathOTPSecret                              = "otp_secret"
	StashPathPasscodeEmail                          = "sticky.passcode_email"
	StashPathPasscodeID                             = "sticky.passcode_id"
	StashPathPasscodeTemplate                       = "passcode_template"
	StashPathSecurityKey                            = "security_key"
	StashPathSkipUserCreation                       = "skip_user_creation"
	StashPathUserHasEmails                          = "user_has_emails"
	StashPathUserHasOTPSecret                       = "user_hat_otp_secret"
	StashPathUserHasPassword                        = "user_has_password"
	StashPathUserHasSecurityKeys                    = "user_has_security_keys"
	StashPathUserHasUsername                        = "user_has_username"
	StashPathUserHasWebauthnCredential              = "user_has_webauthn_credential"
	StashPathUserID                                 = "user_id"
	StashPathUserIdentification                     = "user_identification"
	StashPathUsername                               = "username"
	StashPathWebauthnAvailable                      = "webauthn_available"
	StashPathWebauthnConditionalMediationAvailable  = "webauthn_conditional_mediation_available"
	StashPathWebauthnCredential                     = "webauthn_credential"
	StashPathWebauthnPlatformAuthenticatorAvailable = "webauthn_platform_authenticator_available"
	StashPathWebauthnSessionDataID                  = "webauthn_session_data_id"
)
