database:
  user: hanko
  password: hanko
  host: postgresd
  port: 5432
  dialect: postgres
email_delivery:
  smtp:
    host: "mail"
    port: "1025"
  from_address: noreply@hanko.io
secrets:
  keys:
    - abcedfghijklmnopqrstuvwxyz
service:
  name: Hanko Authentication Service
webauthn:
  relying_party:
    origins:
      - "http://localhost:8888"
session:
  cookie:
    secure: false # is needed for safari, because safari does not store secure cookies on localhost
server:
  public:
    cors:
      allow_origins:
        - "http://localhost:8888"
