// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/_middleware.ts";
import * as $2 from "./routes/api/todo/[id].ts";
import * as $3 from "./routes/api/todo/index.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/profile.tsx";
import * as $6 from "./routes/todo.tsx";
import * as $$0 from "./islands/Login.tsx";
import * as $$1 from "./islands/LogoutButton.tsx";
import * as $$2 from "./islands/Profile.tsx";
import * as $$3 from "./islands/TodoList.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/_middleware.ts": $1,
    "./routes/api/todo/[id].ts": $2,
    "./routes/api/todo/index.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/profile.tsx": $5,
    "./routes/todo.tsx": $6,
  },
  islands: {
    "./islands/Login.tsx": $$0,
    "./islands/LogoutButton.tsx": $$1,
    "./islands/Profile.tsx": $$2,
    "./islands/TodoList.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
