services:
  todo-backend:
    build: ../../frontend/examples/express
    ports:
      - "8002:8002"
    environment:
      - HANKO_API_URL=http://hanko:8000
    networks:
      - intranet
  todo-frontend:
    build: ../../frontend/examples/nextjs-app
    ports:
      - "8889:8889"
    networks:
      - intranet
