name: frontend-sdk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1

      - name: Install dependencies
        working-directory: ./frontend-sdk
        run: npm ci

      - name: Build
        working-directory: ./frontend-sdk
        run: npm run build

      - name: Run tests
        working-directory: ./frontend-sdk
        run: npm test
